[workspace]
members = ["bike-analysis", "bike-decoder", "bike-decoder-pyo3", "bike-trials"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]

[profile.test]
opt-level = 2

[profile.bench]
