[package]
name = "bike_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nohash-hasher = "0.2"
num = "0.4"
num-integer = "0.1"
petgraph = "0.6"
rand = "0.8"
rand_xoshiro = "0.6"

[profile.release]
debug = true
