[package]
name = "bike_decoder"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of a BGF decoder for QC-MDPC codes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
num = "0.4"
num-integer = "0.1"
petgraph = "0.6"
rand = "0.8"
rand_core = "0.6.4"
rand_xoshiro = "0.6"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_arrays = "0.1"
serde_json = "1.0"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "benchmarks"
harness = false
