[workspace]
members = ["bike_decoder", "bike_trials"]

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
incremental = true

[profile.test]
opt-level = 2
incremental = true

[profile.bench]
incremental = true
