[package]
name = "absorbing"
version = "0.1.0"
edition = "2021"
description = "Analysis of absorbing sets for QC-MDPC codes"
license = "MIT"

[dependencies]
bike_decoder = { path = "../bike_decoder" }
serde = "1.0.152"
serde_json = "1.0.91"
